// Diese Datei ist eine Datenbank mit jeweils 6 Tieren für die 7 verschiedenen Kontinente und all ihren Attributen
export const animal = [
    {
        "name": "Afrikanischer Elefant",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Proboscidea",
            "family": "Elephantidae",
            "genus": "Loxodonta",
            "scientific_name": "Loxodonta africana"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Gräser, Früchte, Rinde",
            "name_of_young": "Kalb",
            "group_behavior": "Herde",
            "estimated_population_size": "415.000",
            "biggest_threat": "Wilderei, Lebensraumverlust",
            "most_distinctive_feature": "Große Ohren und Rüssel",
            "gestation_period": "22 Monate",
            "habitat": "Savanne, Wald",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Afrikanischer Elefant",
            "number_of_species": "2",
            "location": "Afrika",
            "slogan": "Größtes Landtier der Erde!",
            "group": "Säugetier",
            "color": "Grau",
            "skin_type": "Leder",
            "top_speed": "25 mph",
            "lifespan": "60-70 Jahre",
            "weight": "2.000kg - 6.000kg",
            "height": "2.5m - 4m",
            "age_of_sexual_maturity": "10-12 Jahre",
            "age_of_weaning": "2-3 Jahre"
        }
    },
    {
        "name": "Polarbär",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Ursidae",
            "genus": "Ursus",
            "scientific_name": "Ursus maritimus"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Robben, Fische",
            "name_of_young": "Junges",
            "group_behavior": "Einzeln",
            "estimated_population_size": "22.000 - 31.000",
            "biggest_threat": "Klimawandel",
            "most_distinctive_feature": "Weißes Fell und schwarze Haut",
            "gestation_period": "8 Monate (inkl. verzögerter Einnistung)",
            "habitat": "Arktisches Meereis",
            "diet": "Fleischfresser",
            "average_litter_size": "2",
            "lifestyle": "Tag-/Nachtaktiv (flexibel)",
            "common_name": "Polarbär",
            "number_of_species": "1",
            "location": "Arktischer Polarkreis",
            "slogan": "Herrscher des eisigen Nordens!",
            "group": "Säugetier",
            "color": "Weiß",
            "skin_type": "Fell",
            "top_speed": "25 mph",
            "lifespan": "20-30 Jahre",
            "weight": "350kg - 700kg",
            "height": "2.4m - 3m (aufgerichtet)",
            "age_of_sexual_maturity": "4-5 Jahre",
            "age_of_weaning": "2 - 2,5 Jahre"
        }
    },
    {
        "name": "Kaiserpinguin",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Aves",
            "order": "Sphenisciformes",
            "family": "Spheniscidae",
            "genus": "Aptenodytes",
            "scientific_name": "Aptenodytes forsteri"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Fische, Krill, Tintenfische",
            "name_of_young": "Küken",
            "group_behavior": "Kolonien",
            "estimated_population_size": "595.000",
            "biggest_threat": "Klimawandel, Lebensraumverlust",
            "most_distinctive_feature": "Größte Pinguinart",
            "gestation_period": "Eibrut ca. 64 Tage",
            "habitat": "Antarktisches Eis und Gewässer",
            "diet": "Fleischfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Kaiserpinguin",
            "number_of_species": "1",
            "location": "Antarktis",
            "slogan": "Ein königlicher Vogel des Eises!",
            "group": "Vogel",
            "color": "Schwarz, Weiß, Gelb",
            "skin_type": "Federn",
            "top_speed": "5-6 mph (im Wasser)",
            "lifespan": "15-20 Jahre",
            "weight": "22kg - 45kg",
            "height": "1.1m - 1.3m",
            "age_of_sexual_maturity": "4 Jahre",
            "age_of_weaning": "5 Monate"
        }
    },
    {
        "name": "Känguru",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Diprotodontia",
            "family": "Macropodidae",
            "genus": "Macropus",
            "scientific_name": "Macropus rufus"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Gräser",
            "name_of_young": "Junges (Joey)",
            "group_behavior": "Gruppe (Mob)",
            "estimated_population_size": "Über 50 Millionen (alle Arten zusammen)",
            "biggest_threat": "Lebensraumverlust, Jagd",
            "most_distinctive_feature": "Kräftige Hinterbeine und langer Schwanz",
            "gestation_period": "33 Tage",
            "habitat": "Grasland, Buschland",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tag-/Nachtaktiv",
            "common_name": "Känguru",
            "number_of_species": "4 (Hauptarten)",
            "location": "Australien",
            "slogan": "Springende Wunder des Outbacks!",
            "group": "Säugetier",
            "color": "Braun, Grau, Rot",
            "skin_type": "Fell",
            "top_speed": "35 mph",
            "lifespan": "8-12 Jahre (in der Wildnis)",
            "weight": "18kg - 90kg",
            "height": "0.5m - 1.8m",
            "age_of_sexual_maturity": "1-2 Jahre",
            "age_of_weaning": "1 Jahr"
        }
    },
    {
        "name": "Große Anakonda",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Reptilia",
            "order": "Squamata",
            "family": "Boidae",
            "genus": "Eunectes",
            "scientific_name": "Eunectes murinus"
        },
        "locations": [
            "Südamerika"
        ],
        "characteristics": {
            "prey": "Fische, Vögel, Säugetiere",
            "name_of_young": "Jungtier (Schlüpfling)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Unbekannt",
            "biggest_threat": "Lebensraumzerstörung",
            "most_distinctive_feature": "Massive Körperfülle und aquatische Lebensweise",
            "gestation_period": "6-7 Monate (ovovivipar)",
            "habitat": "Sümpfe, Marschen, Flüsse",
            "diet": "Fleischfresser",
            "average_litter_size": "20-40",
            "lifestyle": "Nachtaktiv",
            "common_name": "Anakonda",
            "number_of_species": "4",
            "location": "Südamerika",
            "slogan": "Eine der schwersten Schlangen der Erde!",
            "group": "Reptil",
            "color": "Grün, Braun, Schwarz",
            "skin_type": "Schuppen",
            "top_speed": "5 mph (im Wasser)",
            "lifespan": "10-30 Jahre",
            "weight": "Bis zu 227kg",
            "height": "Bis zu 6-9m Länge",
            "age_of_sexual_maturity": "3-4 Jahre",
            "age_of_weaning": "N/A"
        }
    },
    {
        "name": "Bengalischer Tiger",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Felidae",
            "genus": "Panthera",
            "scientific_name": "Panthera tigris tigris"
        },
        "locations": [
            "Asien"
        ],
        "characteristics": {
            "prey": "Hirsche, Wildschweine, Büffel",
            "name_of_young": "Junges",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Ca. 2.500 (in freier Wildbahn)",
            "biggest_threat": "Wilderei, Lebensraumverlust",
            "most_distinctive_feature": "Orangefarbenes Fell mit schwarzen Streifen",
            "gestation_period": "103 Tage",
            "habitat": "Tropischer Regenwald, Grasland",
            "diet": "Fleischfresser",
            "average_litter_size": "2-4",
            "lifestyle": "Nachtaktiv",
            "common_name": "Bengalischer Tiger",
            "number_of_species": "6 (Tiger-Unterarten)",
            "location": "Asien",
            "slogan": "Majestätischer gestreifter Jäger!",
            "group": "Säugetier",
            "color": "Orange, Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "40 mph",
            "lifespan": "8-10 Jahre (wild)",
            "weight": "110kg - 230kg",
            "height": "1,5m - 2,9m (inkl. Schwanzlänge)",
            "age_of_sexual_maturity": "3-4 Jahre",
            "age_of_weaning": "6 Monate"
        }
    },
    {
        "name": "Eurasischer Wolf",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Canidae",
            "genus": "Canis",
            "scientific_name": "Canis lupus"
        },
        "locations": [
            "Nordamerika",
            "Europa",
            "Asien"
        ],
        "characteristics": {
            "prey": "Hirsche, Elche, Bisons, Kleine Säugetiere",
            "name_of_young": "Welpe",
            "group_behavior": "Rudel",
            "estimated_population_size": "200.000 (weltweit geschätzt)",
            "biggest_threat": "Konflikte mit Menschen, Lebensraumverlust",
            "most_distinctive_feature": "Heulen als Lautäußerung",
            "gestation_period": "63 Tage",
            "habitat": "Wälder, Tundra, Grasland",
            "diet": "Fleischfresser",
            "average_litter_size": "4-6",
            "lifestyle": "Tag-/Nachtaktiv",
            "common_name": "Grauwolf",
            "number_of_species": "Über 30 Unterarten",
            "location": "Nordhalbkugel",
            "slogan": "Ikonischer Rudeljäger!",
            "group": "Säugetier",
            "color": "Grau, Weiß, Schwarz, Braun",
            "skin_type": "Fell",
            "top_speed": "31-37 mph",
            "lifespan": "6-8 Jahre (wild)",
            "weight": "23kg - 68kg",
            "height": "1m - 1,6m (Kopf-Rumpf-Länge)",
            "age_of_sexual_maturity": "2 Jahre",
            "age_of_weaning": "6-8 Wochen"
        }
    },
    {
        "name": "Giraffe",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Artiodactyla",
            "family": "Giraffidae",
            "genus": "Giraffa",
            "scientific_name": "Giraffa camelopardalis"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Blätter, Früchte, Blüten",
            "name_of_young": "Kalb",
            "group_behavior": "Herde",
            "estimated_population_size": "Ca. 68.000",
            "biggest_threat": "Lebensraumverlust, Wilderei",
            "most_distinctive_feature": "Längster Hals aller Tiere",
            "gestation_period": "15 Monate",
            "habitat": "Savanne, Waldland",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Giraffe",
            "number_of_species": "1 (mehrere umstrittene Unterarten)",
            "location": "Afrika",
            "slogan": "Überragende Ikonen der Savanne!",
            "group": "Säugetier",
            "color": "Hellbraun, Braun, Orange, Weiß",
            "skin_type": "Fell",
            "top_speed": "35 mph",
            "lifespan": "20-25 Jahre",
            "weight": "800kg - 1.200kg",
            "height": "4,5m - 6m",
            "age_of_sexual_maturity": "3-4 Jahre",
            "age_of_weaning": "9-12 Monate"
        }
    },
    {
        "name": "Komodowaran",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Reptilia",
            "order": "Squamata",
            "family": "Varanidae",
            "genus": "Varanus",
            "scientific_name": "Varanus komodoensis"
        },
        "locations": [
            "Asien"
        ],
        "characteristics": {
            "prey": "Hirsche, Schweine, Wasserbüffel",
            "name_of_young": "Jungtier (Schlüpfling)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "6.000",
            "biggest_threat": "Lebensraumverlust, Menschliche Aktivitäten",
            "most_distinctive_feature": "Giftiger Speichel und enorme Größe",
            "gestation_period": "7-8 Monate (Eier ~8 Monate bebrütet)",
            "habitat": "Tropische Savanne, Wald",
            "diet": "Fleischfresser",
            "average_litter_size": "15-30 Eier",
            "lifestyle": "Tagaktiv",
            "common_name": "Komodowaran",
            "number_of_species": "1",
            "location": "Komodo-Inseln, Indonesien",
            "slogan": "Die größte lebende Echse!",
            "group": "Reptil",
            "color": "Grau, Braun, Grün",
            "skin_type": "Schuppen",
            "top_speed": "13 mph",
            "lifespan": "30 Jahre",
            "weight": "70kg - 90kg",
            "height": "2m - 3m Länge",
            "age_of_sexual_maturity": "5-7 Jahre",
            "age_of_weaning": "N/A"
        }
    },
    {
        "name": "Jaguar",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Felidae",
            "genus": "Panthera",
            "scientific_name": "Panthera onca"
        },
        "locations": [
            "Südamerika",
            "Nordamerika"
        ],
        "characteristics": {
            "prey": "Hirsche, Nabelschweine, Capybaras",
            "name_of_young": "Junges",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Ca. 15.000",
            "biggest_threat": "Lebensraumverlust, Wilderei",
            "most_distinctive_feature": "Kraftvolle Kiefer und Rosettenmuster",
            "gestation_period": "93-105 Tage",
            "habitat": "Regenwälder, Feuchtgebiete",
            "diet": "Fleischfresser",
            "average_litter_size": "2-4",
            "lifestyle": "Nachtaktiv",
            "common_name": "Jaguar",
            "number_of_species": "1",
            "location": "Amerika",
            "slogan": "Heimlicher Jäger des Dschungels!",
            "group": "Säugetier",
            "color": "Gelb, Braun, Schwarz",
            "skin_type": "Fell",
            "top_speed": "50 mph",
            "lifespan": "12-15 Jahre (wild)",
            "weight": "56kg - 96kg",
            "height": "1,2m - 1,85m (inkl. Schwanz)",
            "age_of_sexual_maturity": "2-3 Jahre",
            "age_of_weaning": "3 Monate"
        }
    },
    {
        "name": "Großer Panda",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Ursidae",
            "genus": "Ailuropoda",
            "scientific_name": "Ailuropoda melanoleuca"
        },
        "locations": [
            "Asien"
        ],
        "characteristics": {
            "prey": "Bambus, Gelegentlich kleine Nagetiere",
            "name_of_young": "Junges",
            "group_behavior": "Einzeln",
            "estimated_population_size": "1.800 (in freier Wildbahn)",
            "biggest_threat": "Lebensraumverlust",
            "most_distinctive_feature": "Schwarz-weißer Pelz",
            "gestation_period": "95-160 Tage",
            "habitat": "Gemäßigte Mischwälder",
            "diet": "Allesfresser (überwiegend Bambus)",
            "average_litter_size": "1-2",
            "lifestyle": "Tag-/Nachtaktiv (flexibel)",
            "common_name": "Großer Panda",
            "number_of_species": "1",
            "location": "China",
            "slogan": "Geliebtes Symbol des Artenschutzes!",
            "group": "Säugetier",
            "color": "Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "20 mph (kurze Sprints)",
            "lifespan": "20 Jahre (wild), bis zu 30 in Gefangenschaft",
            "weight": "70kg - 120kg",
            "height": "1,2m - 1,9m (Länge)",
            "age_of_sexual_maturity": "4-8 Jahre",
            "age_of_weaning": "8-9 Monate"
        }
    },
    {
        "name": "Flusspferd",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Artiodactyla",
            "family": "Hippopotamidae",
            "genus": "Hippopotamus",
            "scientific_name": "Hippopotamus amphibius"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Gräser",
            "name_of_young": "Kalb",
            "group_behavior": "Gruppe (Pod)",
            "estimated_population_size": "115.000 - 130.000",
            "biggest_threat": "Lebensraumverlust, Wilderei",
            "most_distinctive_feature": "Massiver Körper und großes Maul",
            "gestation_period": "8 Monate",
            "habitat": "Flüsse, Seen",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Nachtaktiv",
            "common_name": "Flusspferd",
            "number_of_species": "1 (mit Unterarten)",
            "location": "Subsahara-Afrika",
            "slogan": "Riesige Flussbewohner mit Temperament!",
            "group": "Säugetier",
            "color": "Grau, Braun, Rötlich",
            "skin_type": "Leder",
            "top_speed": "19 mph",
            "lifespan": "40-50 Jahre",
            "weight": "1.500kg - 1.800kg",
            "height": "3,3m - 5m (Länge), ~1,5m hoch",
            "age_of_sexual_maturity": "7-9 Jahre",
            "age_of_weaning": "8 Monate"
        }
    },
    {
        "name": "Panzernashorn",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Perissodactyla",
            "family": "Rhinocerotidae",
            "genus": "Rhinoceros",
            "scientific_name": "Rhinoceros unicornis"
        },
        "locations": [
            "Asien"
        ],
        "characteristics": {
            "prey": "Gräser, Obst, Blätter",
            "name_of_young": "Kalb",
            "group_behavior": "Einzeln",
            "estimated_population_size": "3.600",
            "biggest_threat": "Wilderei wegen des Horns",
            "most_distinctive_feature": "Einzelnes schwarzes Horn und panzerartige Haut",
            "gestation_period": "16 Monate",
            "habitat": "Grasland, Sumpfige Gebiete",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tag-/Nachtaktiv",
            "common_name": "Indisches Nashorn",
            "number_of_species": "1 (in der Gattung Rhinoceros), insgesamt 5 Nashorn-Arten",
            "location": "Indischer Subkontinent",
            "slogan": "Gepanzerte Riesen der Grasländer!",
            "group": "Säugetier",
            "color": "Grau, Braun",
            "skin_type": "Dicke Haut",
            "top_speed": "30 mph",
            "lifespan": "35-45 Jahre",
            "weight": "1.800kg - 2.700kg",
            "height": "1,75m - 2m an der Schulter",
            "age_of_sexual_maturity": "5-7 Jahre",
            "age_of_weaning": "1-2 Jahre"
        }
    },
    {
        "name": "Schimpanse",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Primates",
            "family": "Hominidae",
            "genus": "Pan",
            "scientific_name": "Pan troglodytes"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Früchte, Blätter, Insekten, Kleine Säugetiere",
            "name_of_young": "Säugling (Infant)",
            "group_behavior": "Gruppe (Truppe)",
            "estimated_population_size": "200.000 - 300.000",
            "biggest_threat": "Lebensraumzerstörung, Buschfleischhandel",
            "most_distinctive_feature": "Hohe Intelligenz, Werkzeuggebrauch",
            "gestation_period": "230 Tage",
            "habitat": "Tropischer Regenwald, Wälder",
            "diet": "Allesfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Schimpanse",
            "number_of_species": "1 (4 Unterarten)",
            "location": "Zentral- und Westafrika",
            "slogan": "Nächste lebende Verwandte des Menschen!",
            "group": "Säugetier",
            "color": "Schwarz, Bräunlich",
            "skin_type": "Behaart",
            "top_speed": "25 mph",
            "lifespan": "40-50 Jahre (wild)",
            "weight": "32kg - 60kg",
            "height": "0,9m - 1,2m",
            "age_of_sexual_maturity": "8-10 Jahre",
            "age_of_weaning": "3-4 Jahre"
        }
    },
    {
        "name": "Polarfuchs",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Canidae",
            "genus": "Vulpes",
            "scientific_name": "Vulpes lagopus"
        },
        "locations": [
            "Nordamerika",
            "Asien"
        ],
        "characteristics": {
            "prey": "Lemminge, Wühlmäuse, Fische, Seevögel",
            "name_of_young": "Junges (Kit oder Pup)",
            "group_behavior": "Einzeln oder Paare",
            "estimated_population_size": "Mehrere Hunderttausend",
            "biggest_threat": "Klimawandel",
            "most_distinctive_feature": "Dichtes Fell, das die Farbe wechselt",
            "gestation_period": "49-57 Tage",
            "habitat": "Arktische Tundra",
            "diet": "Allesfresser",
            "average_litter_size": "5-10",
            "lifestyle": "Tag-/Nachtaktiv",
            "common_name": "Polarfuchs",
            "number_of_species": "1",
            "location": "Arktische Regionen der Nordhalbkugel",
            "slogan": "Meister der gefrorenen Tundra!",
            "group": "Säugetier",
            "color": "Weiß (Winter), Braun/Grau (Sommer)",
            "skin_type": "Fell",
            "top_speed": "30 mph",
            "lifespan": "3-6 Jahre (wild)",
            "weight": "2,5kg - 9kg",
            "height": "46cm - 68cm (Körperlänge)",
            "age_of_sexual_maturity": "10 Monate",
            "age_of_weaning": "6 Wochen"
        }
    },
    {
        "name": "Gorilla",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Primates",
            "family": "Hominidae",
            "genus": "Gorilla",
            "scientific_name": "Gorilla beringei / Gorilla gorilla"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Früchte, Blätter, Stängel",
            "name_of_young": "Säugling (Infant)",
            "group_behavior": "Gruppe (Truppe)",
            "estimated_population_size": "100.000 (Westlich), ~1.000 (Berggorillas)",
            "biggest_threat": "Lebensraumverlust, Wilderei",
            "most_distinctive_feature": "Kräftiger Körperbau und Intelligenz",
            "gestation_period": "257 Tage",
            "habitat": "Tropische Wälder",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Gorilla",
            "number_of_species": "2 (Östlich & Westlich) plus Unterarten",
            "location": "Zentralafrika",
            "slogan": "Sanfte Riesen des Waldes!",
            "group": "Säugetier",
            "color": "Schwarz, Bräunlich",
            "skin_type": "Behaart",
            "top_speed": "20-25 mph",
            "lifespan": "35-40 Jahre (wild)",
            "weight": "100kg - 200kg",
            "height": "1,25m - 1,8m",
            "age_of_sexual_maturity": "10-12 Jahre",
            "age_of_weaning": "3-4 Jahre"
        }
    },
    {
        "name": "Afrikanischer Strauß",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Aves",
            "order": "Struthioniformes",
            "family": "Struthionidae",
            "genus": "Struthio",
            "scientific_name": "Struthio camelus"
        },
        "locations": [
            "Afrika"
        ],
        "characteristics": {
            "prey": "Samen, Gras, Insekten",
            "name_of_young": "Küken",
            "group_behavior": "Gruppe (Herde)",
            "estimated_population_size": "2 Millionen (Farm + Wild, weniger in der Wildnis)",
            "biggest_threat": "Lebensraumverlust, Jagd",
            "most_distinctive_feature": "Größter und schnell laufender Vogel",
            "gestation_period": "Brutzeit ca. 42 Tage",
            "habitat": "Savanne, Wüste",
            "diet": "Allesfresser",
            "average_litter_size": "Ca. 10 Eier im Gemeinschaftsnest",
            "lifestyle": "Tagaktiv",
            "common_name": "Strauß",
            "number_of_species": "2 (Gewöhnlicher & Somali-Strauß)",
            "location": "Afrika",
            "slogan": "Flugunfähige Schnellläufer der Savanne!",
            "group": "Vogel",
            "color": "Schwarz, Weiß, Braun",
            "skin_type": "Federn",
            "top_speed": "43 mph",
            "lifespan": "40-45 Jahre (wild)",
            "weight": "63kg - 145kg",
            "height": "2m - 2,8m",
            "age_of_sexual_maturity": "2-4 Jahre",
            "age_of_weaning": "Mit ein paar Monaten selbstständig"
        }
    },
    {
        "name": "Koala",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Diprotodontia",
            "family": "Phascolarctidae",
            "genus": "Phascolarctos",
            "scientific_name": "Phascolarctos cinereus"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Eukalyptusblätter",
            "name_of_young": "Junges (Joey)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Ca. 330.000",
            "biggest_threat": "Lebensraumverlust, Krankheiten",
            "most_distinctive_feature": "Flauschige Ohren und löffelförmige Nase",
            "gestation_period": "35 Tage",
            "habitat": "Eukalyptuswälder",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1",
            "lifestyle": "Nachtaktiv",
            "common_name": "Koala",
            "number_of_species": "1",
            "location": "Ost-Australien",
            "slogan": "Verschlafene Ikonen aus Down Under!",
            "group": "Säugetier",
            "color": "Grau, Weiß",
            "skin_type": "Fell",
            "top_speed": "15 mph (kurze Sprints)",
            "lifespan": "10-15 Jahre (wild)",
            "weight": "4kg - 15kg",
            "height": "60cm - 85cm",
            "age_of_sexual_maturity": "2-3 Jahre",
            "age_of_weaning": "6-7 Monate"
        }
    },
    {
        "name": "Europäischer Dachs",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Mustelidae",
            "genus": "Meles",
            "scientific_name": "Meles meles"
        },
        "locations": [
            "Europa"
        ],
        "characteristics": {
            "prey": "Regenwürmer, Kleine Säugetiere, Insekten",
            "name_of_young": "Junges (Cub)",
            "group_behavior": "Sozial (Clans)",
            "estimated_population_size": "Weit verbreitet und häufig",
            "biggest_threat": "Lebensraumverlust, Bestandskontrolle (Bejagung)",
            "most_distinctive_feature": "Schwarz-weiß gestreiftes Gesicht",
            "gestation_period": "7-8 Wochen (verzögerte Einnistung)",
            "habitat": "Wälder, Heckenlandschaften, Ackerland",
            "diet": "Allesfresser",
            "average_litter_size": "1-5",
            "lifestyle": "Nachtaktiv",
            "common_name": "Europäischer Dachs",
            "number_of_species": "1 (in Gattung Meles, mit Unterarten)",
            "location": "Europa und Teile Asiens",
            "slogan": "Gestreifte Grabbler der Nacht!",
            "group": "Säugetier",
            "color": "Grau, Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "19 mph",
            "lifespan": "5-8 Jahre (wild), bis zu 14 in Gefangenschaft",
            "weight": "7kg - 13kg",
            "height": "60cm - 80cm (Körperlänge)",
            "age_of_sexual_maturity": "1-2 Jahre",
            "age_of_weaning": "2-3 Monate"
        }
    },
    {
        "name": "Seeleopard",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Phocidae",
            "genus": "Hydrurga",
            "scientific_name": "Hydrurga leptonyx"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Pinguine, Fische, Krill, Robben",
            "name_of_young": "Junges (Pup)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "220.000 - 440.000",
            "biggest_threat": "Klimawandel, Schwertwale (Orcas)",
            "most_distinctive_feature": "Großes Maul und geflecktes Fell",
            "gestation_period": "9 Monate",
            "habitat": "Antarktische Gewässer",
            "diet": "Fleischfresser",
            "average_litter_size": "1",
            "lifestyle": "Tag- und Nachtaktiv",
            "common_name": "Leopardseehund",
            "number_of_species": "1",
            "location": "Antarktis",
            "slogan": "Ein furchterregender Jäger der Antarktis!",
            "group": "Säugetier",
            "color": "Grau, Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "25 mph",
            "lifespan": "12-26 Jahre",
            "weight": "200kg - 600kg",
            "height": "2,5m - 3,5m",
            "age_of_sexual_maturity": "3-6 Jahre",
            "age_of_weaning": "4 Wochen"
        }
    },
    {
        "name": "Antarktischer Krill",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Arthropoda",
            "class": "Malacostraca",
            "order": "Euphausiacea",
            "family": "Euphausiidae",
            "genus": "Euphausia",
            "scientific_name": "Euphausia superba"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Phytoplankton, Algen",
            "name_of_young": "Nauplius",
            "group_behavior": "Schwarm",
            "estimated_population_size": "500 Billionen",
            "biggest_threat": "Überfischung, Klimawandel",
            "most_distinctive_feature": "Kleiner garnelenartiger Körper mit Biolumineszenz",
            "gestation_period": "5-10 Tage",
            "habitat": "Kaltes antarktisches Wasser",
            "diet": "Pflanzenfresser",
            "average_litter_size": "Tausende Eier",
            "lifestyle": "Nachtaktiv",
            "common_name": "Antarktischer Krill",
            "number_of_species": "1",
            "location": "Antarktischer Ozean",
            "slogan": "Grundlage des antarktischen Nahrungsnetzes!",
            "group": "Krebstier",
            "color": "Durchscheinend, Rosa",
            "skin_type": "Exoskelett",
            "top_speed": "5 mph",
            "lifespan": "5-7 Jahre",
            "weight": "Bis zu 2 g",
            "height": "6 cm",
            "age_of_sexual_maturity": "2 Jahre",
            "age_of_weaning": "N/A"
        }
    },
    {
        "name": "Weddellrobbe",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Phocidae",
            "genus": "Leptonychotes",
            "scientific_name": "Leptonychotes weddellii"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Fische, Tintenfische, Krill",
            "name_of_young": "Junges (Pup)",
            "group_behavior": "Einzeln oder in kleinen Gruppen",
            "estimated_population_size": "800.000",
            "biggest_threat": "Klimawandel",
            "most_distinctive_feature": "Runder Körper und kleiner Kopf",
            "gestation_period": "9 Monate",
            "habitat": "Antarktisches Eis und Gewässer",
            "diet": "Fleischfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Weddellrobbe",
            "number_of_species": "1",
            "location": "Antarktis",
            "slogan": "Eines der am südlichsten brütenden Säugetiere!",
            "group": "Säugetier",
            "color": "Grau, Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "7 mph (im Wasser)",
            "lifespan": "20-30 Jahre",
            "weight": "400kg - 600kg",
            "height": "2,5m - 3m",
            "age_of_sexual_maturity": "3-6 Jahre",
            "age_of_weaning": "6 Wochen"
        }
    },
    {
        "name": "Schneesturmvogel",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Aves",
            "order": "Procellariiformes",
            "family": "Procellariidae",
            "genus": "Pagodroma",
            "scientific_name": "Pagodroma nivea"
        },
        "locations": [
            "Antarktis"
        ],
        "characteristics": {
            "prey": "Krill, Fische, Tintenfische",
            "name_of_young": "Küken",
            "group_behavior": "Schwärme",
            "estimated_population_size": "4 Millionen",
            "biggest_threat": "Klimawandel, Fressfeinde",
            "most_distinctive_feature": "Rein weißes Gefieder",
            "gestation_period": "41-49 Tage (Brutzeit)",
            "habitat": "Antarktische Küsten und Eisberge",
            "diet": "Fleischfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Schneesturmvogel",
            "number_of_species": "1",
            "location": "Antarktis",
            "slogan": "Einer der wenigen Vögel, die das ganze Jahr in der Antarktis leben!",
            "group": "Vogel",
            "color": "Weiß",
            "skin_type": "Federn",
            "top_speed": "40 mph",
            "lifespan": "15-20 Jahre",
            "weight": "240g - 460g",
            "height": "30cm - 40cm",
            "age_of_sexual_maturity": "4-6 Jahre",
            "age_of_weaning": "7-8 Wochen"
        }
    },
    {
        "name": "Pfeilgiftfrosch",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Amphibia",
            "order": "Anura",
            "family": "Dendrobatidae",
            "genus": "Dendrobates",
            "scientific_name": "Dendrobatidae"
        },
        "locations": [
            "Südamerika"
        ],
        "characteristics": {
            "prey": "Insekten, Kleine Wirbellose",
            "name_of_young": "Kaulquappe",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Je nach Art unterschiedlich",
            "biggest_threat": "Lebensraumzerstörung, Klimawandel",
            "most_distinctive_feature": "Leuchtend gefärbte Haut",
            "gestation_period": "14-18 Tage (Eientwicklung)",
            "habitat": "Regenwälder",
            "diet": "Fleischfresser",
            "average_litter_size": "5 - 10 Eier",
            "lifestyle": "Tagaktiv",
            "common_name": "Pfeilgiftfrosch",
            "number_of_species": "Über 100",
            "location": "Südamerika",
            "slogan": "Eines der giftigsten Tiere der Erde!",
            "group": "Amphibie",
            "color": "Blau, Gelb, Rot, Grün",
            "skin_type": "Glatt",
            "top_speed": "10 mph",
            "lifespan": "5-15 Jahre",
            "weight": "Weniger als 1g - 30g",
            "height": "1,5cm - 6cm",
            "age_of_sexual_maturity": "1-2 Jahre",
            "age_of_weaning": "N/A"
        }
    },
    {
        "name": "Amazonas-Flussdelfine",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Cetacea",
            "family": "Iniidae",
            "genus": "Inia",
            "scientific_name": "Inia geoffrensis"
        },
        "locations": [
            "Südamerika"
        ],
        "characteristics": {
            "prey": "Fische, Krebstiere",
            "name_of_young": "Kalb",
            "group_behavior": "Einzeln oder kleine Gruppen",
            "estimated_population_size": "Unbekannt",
            "biggest_threat": "Verschmutzung, Lebensraumzerstörung",
            "most_distinctive_feature": "Rosafarbene Färbung und langer Schnabel",
            "gestation_period": "11-13 Monate",
            "habitat": "Süßwasserflüsse",
            "diet": "Fleischfresser",
            "average_litter_size": "1",
            "lifestyle": "Tagaktiv",
            "common_name": "Amazonas-Flussdelfin",
            "number_of_species": "1",
            "location": "Südamerika",
            "slogan": "Der rosafarbene Delfin des Amazonas!",
            "group": "Säugetier",
            "color": "Rosa, Grau",
            "skin_type": "Glatt",
            "top_speed": "18 mph",
            "lifespan": "30-40 Jahre",
            "weight": "85kg - 185kg",
            "height": "1,5m - 2,5m",
            "age_of_sexual_maturity": "6-10 Jahre",
            "age_of_weaning": "1-2 Jahre"
        }
    },
    {
        "name": "Großer Ameisenbär",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Pilosa",
            "family": "Myrmecophagidae",
            "genus": "Myrmecophaga",
            "scientific_name": "Myrmecophaga tridactyla"
        },
        "locations": [
            "Südamerika"
        ],
        "characteristics": {
            "prey": "Ameisen, Termiten",
            "name_of_young": "Junges (Pup)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "Rückläufig",
            "biggest_threat": "Lebensraumverlust, Jagd",
            "most_distinctive_feature": "Langer Rüssel und buschiger Schwanz",
            "gestation_period": "190 Tage",
            "habitat": "Grasland, Regenwälder",
            "diet": "Insektenfresser",
            "average_litter_size": "1",
            "lifestyle": "Tag- und Nachtaktiv",
            "common_name": "Riesenameisenbär",
            "number_of_species": "1",
            "location": "Südamerika",
            "slogan": "Verspeist bis zu 30.000 Ameisen pro Tag!",
            "group": "Säugetier",
            "color": "Braun, Schwarz, Weiß",
            "skin_type": "Fell",
            "top_speed": "30 mph",
            "lifespan": "14-16 Jahre",
            "weight": "22kg - 45kg",
            "height": "1,8m - 2,2m",
            "age_of_sexual_maturity": "2-4 Jahre",
            "age_of_weaning": "6 Monate"
        }
    },
    {
        "name": "Capybara",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Rodentia",
            "family": "Caviidae",
            "genus": "Hydrochoerus",
            "scientific_name": "Hydrochoerus hydrochaeris"
        },
        "locations": [
            "Südamerika"
        ],
        "characteristics": {
            "prey": "Gras, Wasserpflanzen, Früchte",
            "name_of_young": "Junges (Pup)",
            "group_behavior": "Herde",
            "estimated_population_size": "Stabil",
            "biggest_threat": "Jagd, Lebensraumzerstörung",
            "most_distinctive_feature": "Große Körpergröße und Schwimmhäute",
            "gestation_period": "130 - 150 Tage",
            "habitat": "Feuchtgebiete, Grasland",
            "diet": "Pflanzenfresser",
            "average_litter_size": "4 - 5",
            "lifestyle": "Tagaktiv",
            "common_name": "Wasserschwein",
            "number_of_species": "1",
            "location": "Südamerika",
            "slogan": "Das größte Nagetier der Welt!",
            "group": "Säugetier",
            "color": "Braun",
            "skin_type": "Fell",
            "top_speed": "22 mph",
            "lifespan": "8-10 Jahre",
            "weight": "35kg - 66kg",
            "height": "0,5m - 0,6m",
            "age_of_sexual_maturity": "12 - 18 Monate",
            "age_of_weaning": "3 - 4 Monate"
        }
    },
    {
        "name": "Elch",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Artiodactyla",
            "family": "Cervidae",
            "genus": "Alces",
            "scientific_name": "Alces alces"
        },
        "locations": [
            "Nordamerika",
            "Europa"
        ],
        "characteristics": {
            "prey": "Blätter, Zweige, Wasserpflanzen",
            "name_of_young": "Kalb",
            "group_behavior": "Einzeln",
            "estimated_population_size": "1 Million (Nordamerika)",
            "biggest_threat": "Lebensraumverlust, Jagd",
            "most_distinctive_feature": "Großes Geweih und lange Beine",
            "gestation_period": "230 Tage",
            "habitat": "Wälder, Feuchtgebiete",
            "diet": "Pflanzenfresser",
            "average_litter_size": "1 - 2",
            "lifestyle": "Tagaktiv",
            "common_name": "Elch",
            "number_of_species": "1",
            "location": "Nordamerika, Europa, Asien",
            "slogan": "Die größte Hirschart!",
            "group": "Säugetier",
            "color": "Braun",
            "skin_type": "Fell",
            "top_speed": "35 mph",
            "lifespan": "15-25 Jahre",
            "weight": "200kg - 700kg",
            "height": "1,4m - 2,1m",
            "age_of_sexual_maturity": "1,5 - 2 Jahre",
            "age_of_weaning": "6 - 7 Monate"
        }
    },
    {
        "name": "Eurasischer Luchs",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Felidae",
            "genus": "Lynx",
            "scientific_name": "Lynx lynx"
        },
        "locations": [
            "Europa"
        ],
        "characteristics": {
            "prey": "Hirsche, Hasen, Vögel",
            "name_of_young": "Junges (Kitten)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "50.000",
            "biggest_threat": "Lebensraumverlust, Wilderei",
            "most_distinctive_feature": "Pinselohren und dichtes Fell",
            "gestation_period": "67 - 74 Tage",
            "habitat": "Wälder, Berge",
            "diet": "Fleischfresser",
            "average_litter_size": "2 - 4",
            "lifestyle": "Nachtaktiv",
            "common_name": "Eurasischer Luchs",
            "number_of_species": "1",
            "location": "Europa, Asien",
            "slogan": "Ein lautloser Jäger der Wälder!",
            "group": "Säugetier",
            "color": "Braun, Grau",
            "skin_type": "Fell",
            "top_speed": "50 mph",
            "lifespan": "10-20 Jahre",
            "weight": "18kg - 30kg",
            "height": "0,6m - 0,75m",
            "age_of_sexual_maturity": "2 - 3 Jahre",
            "age_of_weaning": "3 - 5 Monate"
        }
    },
    {
        "name": "Europäischer Braunbär",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Mammalia",
            "order": "Carnivora",
            "family": "Ursidae",
            "genus": "Ursus",
            "scientific_name": "Ursus arctos arctos"
        },
        "locations": [
            "Europa"
        ],
        "characteristics": {
            "prey": "Fische, Beeren, Kleine Säugetiere",
            "name_of_young": "Junges (Cub)",
            "group_behavior": "Einzeln",
            "estimated_population_size": "17.000 - 18.000",
            "biggest_threat": "Lebensraumverlust, Menschlicher Konflikt",
            "most_distinctive_feature": "Große Körpergröße und dichtes Fell",
            "gestation_period": "180 - 250 Tage",
            "habitat": "Wälder, Berge",
            "diet": "Allesfresser",
            "average_litter_size": "1 - 3",
            "lifestyle": "Tagaktiv",
            "common_name": "Europäischer Braunbär",
            "number_of_species": "1",
            "location": "Europa, Asien",
            "slogan": "Einer der größten Raubtiere Europas!",
            "group": "Säugetier",
            "color": "Braun",
            "skin_type": "Fell",
            "top_speed": "35 mph",
            "lifespan": "20-30 Jahre",
            "weight": "100kg - 350kg",
            "height": "1,2m - 2,2m",
            "age_of_sexual_maturity": "3 - 5 Jahre",
            "age_of_weaning": "1 - 2 Jahre"
        }
    },
    {
        "name": "Dingo",
        "taxonomy": {
            "kingdom": "Tierreich",
            "phylum": "Chordatiere",
            "class": "Säugetiere",
            "order": "Raubtiere",
            "family": "Hundeartige",
            "genus": "Canis",
            "scientific_name": "Canis lupus dingo"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Kleine Säugetiere, Vögel, Reptilien",
            "name_of_young": "Welpe",
            "group_behavior": "Rudel",
            "estimated_population_size": "Variabel",
            "biggest_threat": "Hybridisierung mit Haushunden, Lebensraumverlust",
            "most_distinctive_feature": "Schlanker Körperbau und buschiger Schwanz",
            "gestation_period": "63 Tage",
            "habitat": "Wüsten, Grasländer, Wälder",
            "diet": "Fleischfresser",
            "average_litter_size": "4 - 6",
            "lifestyle": "Nachtaktiv",
            "common_name": "Dingo",
            "number_of_species": "1",
            "location": "Australien",
            "slogan": "Australiens wilder Hund!",
            "group": "Säugetier",
            "color": "Gelb, Braun, Schwarz",
            "skin_type": "Fell",
            "top_speed": "37 mph (ca. 60 km/h)",
            "lifespan": "10-13 Jahre",
            "weight": "10 kg - 20 kg",
            "height": "0,5 m - 0,7 m",
            "age_of_sexual_maturity": "1 - 3 Jahre",
            "age_of_weaning": "6 - 8 Wochen"
        }
    },
    {
        "name": "Beutelteufel",
        "taxonomy": {
            "kingdom": "Tierreich",
            "phylum": "Chordatiere",
            "class": "Säugetiere",
            "order": "Dasyuromorphia",
            "family": "Dasyuridae",
            "genus": "Sarcophilus",
            "scientific_name": "Sarcophilus harrisii"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Aas, Kleine Säugetiere, Vögel",
            "name_of_young": "Junges",
            "group_behavior": "Einzelgängerisch",
            "estimated_population_size": "25.000",
            "biggest_threat": "Teufelsgesichts-Tumorerkrankung (DFTD), Lebensraumverlust",
            "most_distinctive_feature": "Kräftige Kiefer und lautes Kreischen",
            "gestation_period": "21 Tage",
            "habitat": "Wälder, Küstengebüsch",
            "diet": "Fleischfresser",
            "average_litter_size": "2 - 4",
            "lifestyle": "Nachtaktiv",
            "common_name": "Tasmanischer Teufel",
            "number_of_species": "1",
            "location": "Australien (Tasmanien)",
            "slogan": "Das größte fleischfressende Beuteltier der Welt!",
            "group": "Säugetier",
            "color": "Schwarz",
            "skin_type": "Fell",
            "top_speed": "8 mph (ca. 13 km/h)",
            "lifespan": "5-7 Jahre",
            "weight": "6 kg - 8 kg",
            "height": "0,5 m",
            "age_of_sexual_maturity": "2 Jahre",
            "age_of_weaning": "4 - 5 Monate"
        }
    },
    {
        "name": "Emu",
        "taxonomy": {
            "kingdom": "Tierreich",
            "phylum": "Chordatiere",
            "class": "Vögel",
            "order": "Casuariiformes",
            "family": "Casuariidae",
            "genus": "Dromaius",
            "scientific_name": "Dromaius novaehollandiae"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Samen, Früchte, Insekten",
            "name_of_young": "Küken",
            "group_behavior": "Schwarm",
            "estimated_population_size": "725.000 - 1.000.000",
            "biggest_threat": "Lebensraumzerstörung, Fressfeinde",
            "most_distinctive_feature": "Großer flugunfähiger Körper und lange Beine",
            "gestation_period": "50 - 56 Tage (Eierinkubation)",
            "habitat": "Grasländer, Wälder, Wüsten",
            "diet": "Allesfresser",
            "average_litter_size": "5 - 15 Eier",
            "lifestyle": "Tagaktiv",
            "common_name": "Emu",
            "number_of_species": "1",
            "location": "Australien",
            "slogan": "Der zweitgrößte Vogel der Welt!",
            "group": "Vogel",
            "color": "Braun, Grau",
            "skin_type": "Federn",
            "top_speed": "31 mph (ca. 50 km/h)",
            "lifespan": "10-20 Jahre",
            "weight": "30 kg - 45 kg",
            "height": "1,5 m - 2 m",
            "age_of_sexual_maturity": "2 - 3 Jahre",
            "age_of_weaning": "6 Monate"
        }
    },
    {
        "name": "Leistenkrokodil",
        "taxonomy": {
            "kingdom": "Tierreich",
            "phylum": "Chordatiere",
            "class": "Reptilien",
            "order": "Krokodile",
            "family": "Echte Krokodile",
            "genus": "Crocodylus",
            "scientific_name": "Crocodylus porosus"
        },
        "locations": [
            "Australien"
        ],
        "characteristics": {
            "prey": "Fische, Vögel, Säugetiere",
            "name_of_young": "Junges",
            "group_behavior": "Einzelgängerisch",
            "estimated_population_size": "200.000 - 300.000",
            "biggest_threat": "Wilderei, Lebensraumverlust",
            "most_distinctive_feature": "Große Körpergröße und kräftiger Biss",
            "gestation_period": "80 - 90 Tage (Eierinkubation)",
            "habitat": "Flüsse, Mündungsgebiete, Mangroven",
            "diet": "Fleischfresser",
            "average_litter_size": "40 - 60 Eier",
            "lifestyle": "Nachtaktiv",
            "common_name": "Salzwasserkrokodil",
            "number_of_species": "1",
            "location": "Australien, Südostasien, Indien",
            "slogan": "Das größte lebende Reptil!",
            "group": "Reptil",
            "color": "Dunkelgrün, Braun",
            "skin_type": "Schuppen",
            "top_speed": "20 mph (ca. 32 km/h) (im Wasser)",
            "lifespan": "70-100 Jahre",
            "weight": "400 kg - 1.000 kg",
            "height": "4 m - 7 m",
            "age_of_sexual_maturity": "10 - 12 Jahre",
            "age_of_weaning": "Nicht zutreffend"
        }
    },
    {
        "name": "Weißkopfseeadler",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Aves",
            "order": "Accipitriformes",
            "family": "Accipitridae",
            "genus": "Haliaeetus",
            "scientific_name": "Haliaeetus leucocephalus"
        },
        "locations": [
            "Nordamerika"
        ],
        "characteristics": {
            "prey": "Fische, Kleinsäuger, Vögel",
            "name_of_young": "Adlerjunges",
            "group_behavior": "Monogame Paare, territorial",
            "estimated_population_size": "70.000",
            "biggest_threat": "Umweltverschmutzung, Lebensraumverlust",
            "most_distinctive_feature": "Weißer Kopf, brauner Körper, kräftige Flügel",
            "gestation_period": "Inkubationszeit ca. 35 Tage",
            "habitat": "Gewässernahe Wälder, Küsten und Seen",
            "diet": "Überwiegend Fischfresser",
            "average_litter_size": "1-3",
            "lifestyle": "Tagaktiv",
            "common_name": "Weißkopfseeadler",
            "number_of_species": "1",
            "location": "Nordamerika",
            "slogan": "Symbol der Freiheit!",
            "group": "Vögel",
            "color": "Braun und Weiß",
            "skin_type": "Federn",
            "top_speed": "120 mph (im Sturzflug)",
            "lifespan": "20-30 Jahre",
            "weight": "3-6 kg",
            "height": "70-102 cm",
            "age_of_sexual_maturity": "4-5 Jahre",
            "age_of_weaning": "ca. 10-12 Wochen"
        }
    },
    {
        "name": "Feuersalamander",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Amphibia",
            "order": "Caudata",
            "family": "Salamandridae",
            "genus": "Salamandra",
            "scientific_name": "Salamandra salamandra"
        },
        "locations": [
            "Europa"
        ],
        "characteristics": {
            "prey": "Insekten, Würmer, Schnecken",
            "name_of_young": "Larven",
            "group_behavior": "Einzelgänger, territorial",
            "estimated_population_size": "Zahl unbekannt",
            "biggest_threat": "Lebensraumverlust, Umweltverschmutzung",
            "most_distinctive_feature": "Leuchtend gelbe bis orange Flecken auf schwarzem Hintergrund",
            "gestation_period": "Ei-Entwicklungsdauer ca. 4 Wochen",
            "habitat": "Feuchte Wälder, Bachufer und kalkhaltige Felsen",
            "diet": "Fleischfresser (kleine Wirbellose)",
            "average_litter_size": "50-200",
            "lifestyle": "Nachtaktiv",
            "common_name": "Feuersalamander",
            "number_of_species": "1",
            "location": "Europa",
            "slogan": "Ein farbenfroher Überlebenskünstler der Wälder!",
            "group": "Amphibie",
            "color": "Schwarz mit leuchtend gelben/orangen Flecken",
            "skin_type": "Feucht, glitschig",
            "top_speed": "ca. 1 km/h",
            "lifespan": "15-20 Jahre",
            "weight": "50-150 g",
            "height": "15-20 cm",
            "age_of_sexual_maturity": "3-4 Jahre",
            "age_of_weaning": "Nicht anwendbar"
        }
    },
    {
        "name": "Axolotl",
        "taxonomy": {
            "kingdom": "Animalia",
            "phylum": "Chordata",
            "class": "Amphibia",
            "order": "Caudata",
            "family": "Ambystomatidae",
            "genus": "Ambystoma",
            "scientific_name": "Ambystoma mexicanum"
        },
        "locations": [
            "Nordamerika"
        ],
        "characteristics": {
            "prey": "Kleine Fische, Insekten, Krebstiere",
            "name_of_young": "Larven",
            "group_behavior": "Einzelgänger, gelegentlich in kleinen Gruppen während der Laichzeit",
            "estimated_population_size": "Stark rückläufig in freier Wildbahn",
            "biggest_threat": "Lebensraumverlust, Verschlechterung der Wasserqualität, invasive Arten",
            "most_distinctive_feature": "Externe Kiemen und außergewöhnliche Regenerationsfähigkeit",
            "gestation_period": "Eier schlüpfen nach 14-21 Tagen",
            "habitat": "Kaltwasserige Seen und Kanäle, vor allem im Xochimilco-See (Mexiko-Stadt)",
            "diet": "Fleischfresser (kleine Fische, Insekten, Krebstiere)",
            "average_litter_size": "100-300 Eier",
            "lifestyle": "Wasserlebend, nachtaktiv",
            "common_name": "Axolotl",
            "number_of_species": "1",
            "location": "Mexiko",
            "slogan": "Der Regenerationsmeister der Amphibienwelt!",
            "group": "Amphibie",
            "color": "Variabel, oft rosa, weiß, braun oder schwarz",
            "skin_type": "Glatt und feucht",
            "top_speed": "Nicht besonders schnell",
            "lifespan": "10-15 Jahre (in Gefangenschaft)",
            "weight": "70-100 g",
            "height": "Etwa 23 cm (Körperlänge)",
            "age_of_sexual_maturity": "1-2 Jahre",
            "age_of_weaning": "Nicht anwendbar"
        }
    }
]